// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX4KG6tGZO-uzIUmdJu1LXlw38S_3elwk',
    appId: '1:949030063519:web:1860a0f07edd9026dc01aa',
    messagingSenderId: '949030063519',
    projectId: 'last-2ec02',
    authDomain: 'last-2ec02.firebaseapp.com',
    storageBucket: 'last-2ec02.firebasestorage.app',
    measurementId: 'G-Y8REMJEYNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxye08__Lb8YUPojHYm6Ia09COzb0kD4',
    appId: '1:949030063519:android:05be98b3b93c719adc01aa',
    messagingSenderId: '949030063519',
    projectId: 'last-2ec02',
    storageBucket: 'last-2ec02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_w5b2V7ANzzi6N0ZSuOfzQ-eOgguXF8g',
    appId: '1:949030063519:ios:efee148ca0366ea5dc01aa',
    messagingSenderId: '949030063519',
    projectId: 'last-2ec02',
    storageBucket: 'last-2ec02.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_w5b2V7ANzzi6N0ZSuOfzQ-eOgguXF8g',
    appId: '1:949030063519:ios:efee148ca0366ea5dc01aa',
    messagingSenderId: '949030063519',
    projectId: 'last-2ec02',
    storageBucket: 'last-2ec02.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX4KG6tGZO-uzIUmdJu1LXlw38S_3elwk',
    appId: '1:949030063519:web:be843ae377cbc717dc01aa',
    messagingSenderId: '949030063519',
    projectId: 'last-2ec02',
    authDomain: 'last-2ec02.firebaseapp.com',
    storageBucket: 'last-2ec02.firebasestorage.app',
    measurementId: 'G-P3ZC8XGZ0D',
  );
}
